<a href="https://colab.research.google.com/github/nizardbsk/pythorch-tutorial/blob/main/pytorch_math_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

In [3]:
tensor_a=torch.tensor([1,2,3,4])
tensor_b=torch.tensor([5,6,7,8])

In [4]:
#addition
tensor_a+tensor_b

tensor([ 6,  8, 10, 12])

In [5]:
#addition longhand
torch.add(tensor_b,tensor_a)

tensor([ 6,  8, 10, 12])

In [6]:
#Subtraction
tensor_a-tensor_b

tensor([-4, -4, -4, -4])

In [7]:
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [8]:
#multiplication
tensor_a*tensor_b

tensor([ 5, 12, 21, 32])

In [9]:
torch.mul(tensor_b,tensor_a)

tensor([ 5, 12, 21, 32])

In [10]:
#Divition
tensor_b/tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [11]:
torch.div(tensor_a,tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [12]:
#Reminder
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [13]:
torch.remainder(tensor_a,tensor_b)

tensor([1, 2, 3, 4])

In [14]:
#Exponents
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [15]:
#Reasssignment
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [16]:
tensor_a

tensor([ 6,  8, 10, 12])