<a href="https://colab.research.google.com/github/nizardbsk/pythorch-tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
np1=np.random.rand(3,4)
np1

array([[0.98675123, 0.2636319 , 0.25940014, 0.70901565],
       [0.22742017, 0.56941584, 0.65086939, 0.10945239],
       [0.03645867, 0.00542458, 0.04156702, 0.63546799]])

In [3]:
np1.dtype

dtype('float64')

In [4]:
tensor_2d=torch.randn(3,4)
tensor_2d

tensor([[-0.6339,  0.2387, -0.4729, -0.0387],
        [ 0.7812,  1.4344, -0.3116, -0.0202],
        [-0.9251, -0.1570,  1.5566, -2.2521]])

In [5]:
tensor_3d=torch.zero_(2,3,4)
tensor_3d

TypeError: ignored

In [6]:
tensor_3d=torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
##create tensor out of numpy array
my_tensor=torch.tensor(np1)
my_tensor

tensor([[0.9868, 0.2636, 0.2594, 0.7090],
        [0.2274, 0.5694, 0.6509, 0.1095],
        [0.0365, 0.0054, 0.0416, 0.6355]], dtype=torch.float64)