<a href="https://colab.research.google.com/github/nizardbsk/pythorch-tutorial/blob/main/Tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
my_torch=torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Reshape and view
my_torch=my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [4]:
# Reshape if we don't know the number of items using -1
my_torch2=torch.arange(10)
my_torch2


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
my_torch2=my_torch2.reshape(2,-1)

In [6]:
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [9]:
my_torch3=torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
my_torch4=my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
# tensors with reshape and view ,update
my_torch5=torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
my_torch6=my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
my_torch5[3]=52
my_torch5

tensor([ 0,  1,  2, 52,  4,  5,  6,  7,  8,  9])

In [13]:
my_torch6

tensor([[ 0,  1,  2, 52,  4],
        [ 5,  6,  7,  8,  9]])

In [14]:
# Grab a specefic number
my_torch7=torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
my_torch7[8]

tensor(8)

In [16]:
my_torch8=my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [17]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [18]:
#Return column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])